Python Assignment-1
fbastos231/python pull request #1
Opened 2024-08-31 22:17 UTC by fbastos231

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)

- Part 1: Building the base Anagram Checker
    added solution to anagram_checker. Code converts input strings into lower case, checks length
    of strings, iterates through them and if it finds matching characters adds them to a
    "matching list". The matching list length determines if anagram or not.

- Part 2: Expanding the functionality of the Anagram Checker
    added functionality to function created in part 1. New functio is checking for case
    sensitivity input, if case sensitive do not convert strings into lower case.

## What did you learn from the changes you have made?

for this assignment I applied knowledge I had already acquired in other courses. It was good to review methods such as append, replace and lower.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?

if I somehow used the sort method instead 2 for loops it could save time comparing strings.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?

ensuring spaces and repeat letters were considered. I address these by removing spacing from input strings at the beginning of the code and breaking out of the for loops when a letter was found to avoid counting matches more than once.

## How were these changes tested?

I ran the code locally and tested on examples provided as well as additional examples found at https://en.wikipedia.org/wiki/Anagram

## A reference to a related issue in your repository (if applicable)

## Checklist
- [x] I can confirm that my changes are working as intended

2024-09-11 03:17 UTC, dwz92 requested changes
Your function in Part 1 and 2 have a logic flaw where only word a is checked against word b. This will result in cases where `anagram_checker("Silint", "listen")` returns True when they are clearly not anagram of each other.

2024-09-11 23:48 UTC, fbastos231 commented
> Your function in Part 1 and 2 have a logic flaw where only word a is checked against word b. This will result in cases where `anagram_checker("Silint", "listen")` returns True when they are clearly not anagram of each other.

Understood. I have updated the code to fix the logic flaw. I attempted removing the characters found  in the "b" prior to breaking the second for loop but that seemed too complicated. I ended up simplifying the logic using the sorted function.

2024-09-13 17:56 UTC, dwz92 approved these changes

2024-09-13 18:44 UTC, fbastos231 commented
Approved

2024-09-13 18:44 UTC, merged